name: Deploy Blog

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Variables # 这一步用来测试变量是否存在
        run: |
          if [ -z "${{ secrets.SERVER_HOST }}" ]; then echo "HOST IS MISSING"; else echo "HOST IS PRESENT"; fi

      - name: Remote SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /root/www/my-geek-blog
            git remote set-url origin https://ghp.ci/https://github.com/Leander-Lan/my-geek-blog.git
            git pull origin master
            npm install --legacy-peer-deps
            npx prisma generate
            npm run build
            pm2 restart my-blog || pm2 start npm --name "my-blog" -- start