name: blog

on:
  push:
    branches: [ master ] # 如果你的分支叫 main，请改成 main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          # 注意：这里的名字必须和 GitHub Settings 里的 Secret 名字严格对应
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /root/www/my-geek-blog
            git remote set-url origin https://ghp.ci/https://github.com/Leander-Lan/my-geek-blog.git
            git pull origin master
            npm install --legacy-peer-deps
            npx prisma generate
            npm run build
            pm2 restart my-blog || pm2 start npm --name "my-blog" -- start