- name: Remote SSH
    uses: appleboy/ssh-action@master
    with:
      host: "115.175.37.0" # ğŸ‘ˆ ç›´æ¥å†™æ­» IP å­—ç¬¦ä¸²ï¼Œçœ‹å®ƒè¿˜æŠ¥ä¸æŠ¥ missing host
      username: "root"      # ğŸ‘ˆ ç›´æ¥å†™æ­»ç”¨æˆ·å
      key: ${{ secrets.SERVER_SSH_KEY }}
      port: 22
      script: |
        cd /root/www/my-geek-blog
        git pull origin master
        npm run build
        pm2 restart my-blog